platform :ios, '15.5'
project 'OnDeviceTranslationSample.xcodeproj'

target 'OnDeviceTranslationSample' do
  pod 'GoogleMLKit/Translate', '9.0.0'

  target 'OnDeviceTranslationSampleTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
