name: OnDeviceTranslationSample
options:
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
configFiles:
  Debug: Configs/Base.xcconfig
  Release: Configs/Base.xcconfig
settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    COREML_CODEGEN_LANGUAGE: None
packages:
  OnDeviceTranslationEngine:
    path: ../OnDeviceTranslationEngine
targets:
  OnDeviceTranslationSample:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources
    dependencies:
      - package: OnDeviceTranslationEngine
    info:
      path: Configs/Info.plist
      properties:
        CFBundleDisplayName: On-Device Translator
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_ID)
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        OTHER_LDFLAGS: ["$(inherited)", "-weak_framework", "Translation"]
  OnDeviceTranslationSampleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: OnDeviceTranslationSample
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_ID).tests
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
schemes:
  OnDeviceTranslationSample:
    build:
      targets:
        OnDeviceTranslationSample: all
    test:
      targets:
        - OnDeviceTranslationSampleTests
